#!/usr/bin/env python3
"""Build lightweight, feature-grouped nuBoard result folders."""

from __future__ import annotations

import argparse
import json
import pickle
import re
from collections import OrderedDict
from pathlib import Path


FEATURE_RE = re.compile(r"^FEATURE\s+(\d+)\s*$")
SCENARIO_RE = re.compile(
    r"^[\d.]+\s+\|\s+type:\s+(?P<type>[^|]+?)\s+"
    r"\|\s+name:\s+(?P<token>[^|]+?)\s+\|\s+log:\s+(?P<log>\S+)\s*$"
)


def parse_report(path: Path) -> OrderedDict[str, OrderedDict[str, dict[str, str]]]:
    features: OrderedDict[str, OrderedDict[str, dict[str, str]]] = OrderedDict()
    current_feature: str | None = None

    for line_number, raw_line in enumerate(path.read_text().splitlines(), start=1):
        line = raw_line.strip()
        feature_match = FEATURE_RE.match(line)
        if feature_match:
            current_feature = feature_match.group(1)
            features.setdefault(current_feature, OrderedDict())
            continue

        scenario_match = SCENARIO_RE.match(line)
        if not scenario_match:
            continue
        if current_feature is None:
            raise ValueError(f"Scenario before feature heading on line {line_number}")

        scenario = {key: value.strip() for key, value in scenario_match.groupdict().items()}
        # The report can contain the same scenario more than once due to repeated activations.
        features[current_feature].setdefault(scenario["token"], scenario)

    if not features:
        raise ValueError(f"No feature sections found in {path}")
    return features


def index_simulations(exp_root: Path) -> dict[str, list[Path]]:
    simulations: dict[str, list[Path]] = {}
    for path in exp_root.glob("**/simulation_log/**/*.msgpack.xz"):
        # Do not index links generated by an earlier invocation of this script.
        if "feature_scenarios" in path.parts:
            continue
        token = path.name.removesuffix(".msgpack.xz")
        simulations.setdefault(token, []).append(path)
    for paths in simulations.values():
        paths.sort(key=lambda path: path.stat().st_mtime, reverse=True)
    return simulations


def choose_simulation(paths: list[Path], scenario: dict[str, str]) -> Path | None:
    for path in paths:
        # Expected tail: planner/type/log/token/token.msgpack.xz
        if path.parents[1].name != scenario["log"]:
            continue
        if path.parents[2].name != scenario["type"]:
            continue
        return path
    return None


def build_feature_folder(
    output_root: Path,
    feature_id: str,
    scenarios: OrderedDict[str, dict[str, str]],
    simulation_index: dict[str, list[Path]],
) -> dict[str, object]:
    feature_name = f"feature_{feature_id}"
    # nuBoard exposes this directory level as the scenario-type selector.
    simulation_root = output_root / "simulation_log" / "diffusion_planner" / feature_name

    found: list[str] = []
    missing: list[str] = []
    for token, scenario in scenarios.items():
        source = choose_simulation(simulation_index.get(token, []), scenario)
        if source is None:
            missing.append(token)
            continue

        destination = (
            simulation_root
            / scenario["log"]
            / token
            / source.name
        )
        destination.parent.mkdir(parents=True, exist_ok=True)
        if destination.is_symlink():
            if destination.resolve() != source.resolve():
                destination.unlink()
            else:
                found.append(token)
                continue
        if destination.exists():
            raise FileExistsError(f"Refusing to replace non-link file: {destination}")
        destination.symlink_to(source.resolve())
        found.append(token)

    summary = {
        "feature": int(feature_id),
        "listed_rows_after_deduplication": len(scenarios),
        "available_scenarios": len(found),
        "missing_scenarios": missing,
    }
    summary_path = output_root / "summaries" / feature_name / "summary.json"
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.write_text(json.dumps(summary, indent=2) + "\n")
    return summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("report", type=Path, help="Feature ranking text report")
    parser.add_argument(
        "--exp-root",
        type=Path,
        default=Path("/data/saba/parnia/Project/exp"),
        help="Root containing completed nuPlan simulation results",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path(
            "/data/saba/parnia/Project/exp/exp/simulation/closed_loop_nonreactive_agents/"
            "diffusion_planner/feature_scenarios"
        ),
        help="Destination scanned by run_nuboard.ipynb",
    )
    args = parser.parse_args()

    features = parse_report(args.report)
    simulation_index = index_simulations(args.exp_root)
    args.output_root.mkdir(parents=True, exist_ok=True)
    (args.output_root / "metrics").mkdir(exist_ok=True)
    (args.output_root / "aggregator_metric").mkdir(exist_ok=True)
    summaries = [
        build_feature_folder(args.output_root, feature_id, scenarios, simulation_index)
        for feature_id, scenarios in features.items()
    ]
    (args.output_root / "summary.json").write_text(json.dumps(summaries, indent=2) + "\n")
    manifest = {
        "simulation_main_path": str(args.output_root.resolve()),
        "metric_main_path": str(args.output_root.resolve()),
        "metric_folder": "metrics",
        "aggregator_metric_folder": "aggregator_metric",
        "simulation_folder": "simulation_log",
    }
    (args.output_root / "feature_scenarios.nuboard").write_bytes(pickle.dumps(manifest))

    available = sum(int(summary["available_scenarios"]) for summary in summaries)
    missing = sum(len(summary["missing_scenarios"]) for summary in summaries)
    print(f"Built {len(summaries)} feature folders with {available} scenario links; {missing} missing.")


if __name__ == "__main__":
    main()
